<?php

/**
 * This file is part of vBuilder Framework (vBuilder FW).
 *
 * Copyright (c) 2011 Adam Staněk <adam.stanek@v3net.cz>
 *
 * For more information visit http://www.vbuilder.cz
 *
 * vBuilder FW is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * vBuilder FW is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with vBuilder FW. If not, see <http://www.gnu.org/licenses/>.
 */

namespace vBuilder\Cli;

use Composer\Script\Event;
use Composer\Util\Filesystem;

/**
 * Composer installation scripts
 *
 * @internal
 *
 * @author Adam Staněk (velbloud)
 * @since Jun 5, 2014
 */
class ComposerScripts {

	/**
	 * Creates bootstrap for examples
	 */
	static function postAutoloadDump(Event $e) {

		$config = $e->getComposer()->getConfig();

		$fs = new FileSystem;
		$vendorPath = $fs->normalizePath(realpath($config->get('vendor-dir')));
		$examplesPath = $fs->normalizePath(realpath(__DIR__ . '/../../examples'));
		$relativePath = $fs->findShortestPath($examplesPath, $vendorPath, TRUE);

		$autoloadPath = var_export('/' . $relativePath . '/autoload.php', TRUE);

		$content = <<<BOOTSTRAP_END
<?php

/**
 * @warning This file is automatically generated by Composer.
 * @see vBuilder\Cli\ComposerScripts::postAutoloadDump
 */

return include __DIR__ . $autoloadPath;

BOOTSTRAP_END
;

		file_put_contents($examplesPath . '/bootstrap.php', $content);
	}

}